### ISSUE TITLE
Emulator does not start (wrong dylib path)

### ISSUE THREAD

**Issue by Elijen** [741g/android-emulator-m1-preview#1]
I have tried to run this on Apple Silicon macOS 11.0.1 (20B29). After moving to Application folder it was bouncing for a while, then got blocked by macOS (unknown dev). After allowing it in Security settings it does not start at all.

No error messages.
No processes in Activity Monitor.
No logs in Console (I think, not sure where to look).

Any way I can try to debug this?

**Comment by pepetrejo** [comment]
Hola, a mi me ocurrió exactamente lo mismo en MacBook Pro M1.
Alguna solucion?

**Comment by 741g** [comment]
Hi, please try instead right clicking the app then selecting Open; it then lets you bypass the unknown dev restriction.

**Comment by 741g** [comment]
You can also go to /Applications/Android Emulator.app/Contents/MacOS/ and run ./runemu from there directly

**Comment by Elijen** [comment]
@741g Tried running from CLI and I can at least see an error message. Seems it depends on a library that is not included? The path seems to be hardcoded.

```
./runemu
emulator: Android emulator version 30.3.3.0 (build_id ) (CL:N/A)
dyld: Library not loaded: /Users/lyang/install-qt/lib/libQt5CoreAndroidEmu.5.dylib
  Referenced from: /Applications/Android Emulator.app/Contents/MacOS/emulator/qemu/darwin-aarch64/qemu-system-aarch64
  Reason: image not found
./runemu: line 7:  2430 Abort trap: 6           ./emulator/emulator
```

**Comment by 741g** [comment]
Wow, thanks for catching that! Fix is to go into the Contents/MacOS/emulator/lib64/qt/lib dir and run:

ln -s libQt5CoreAndroidEmu.5.12.1.dylib libQt5CoreAndroidEmu.5.dylib
ln -s libQt5DBusAndroidEmu.5.12.1.dylib libQt5DBusAndroidEmu.5.dylib
ln -s libQt5GuiAndroidEmu.5.12.1.dylib libQt5GuiAndroidEmu.5.dylib
ln -s libQt5NetworkAndroidEmu.5.12.1.dylib libQt5NetworkAndroidEmu.5.dylib
ln -s libQt5PrintSupportAndroidEmu.5.12.1.dylib libQt5PrintSupportAndroidEmu.5.dylib
ln -s libQt5SvgAndroidEmu.5.12.1.dylib libQt5SvgAndroidEmu.5.dylib
ln -s libQt5WidgetsAndroidEmu.5.12.1.dylib libQt5WidgetsAndroidEmu.5.dylib

**Comment by 741g** [comment]
Will send an updated .dmg asap

**Comment by Elijen** [comment]
Thanks, the fix worked and emulator is running fine! 👍

**Comment by 741g** [comment]
Thanks for raising the issue! The release has been updated.

**Comment by pepetrejo** [comment]
El nuevo .dmg funciona bien!!!. Aunque me sale este mensaje de advertencia. <img width="405" alt="Captura de pantalla 2020-12-05 a las 21 09 50" src="https://user-images.githubusercontent.com/75396108/101262669-b50e9b00-3740-11eb-9266-459f97d07dcb.png">
Muchas gracias!!!

**Comment by SlonGL** [comment]
> Wow, thanks for catching that! Fix is to go into the Contents/MacOS/emulator/lib64/qt/lib dir and run:
> ....

I have DTK with CPU A12Z.
After LNs tried to start the emulator. 
But it shows an icon in the doc and stays without any process.
Result:

./runemu
emulator: Android emulator version 30.3.3.0 (build_id ) (CL:N/A)
handleCpuAcceleration: feature check for hvf
cannot add library /Applications/Android Emulator.app/Contents/MacOS/emulator/qemu/darwin-aarch64/lib64/vulkan/libvulkan.dylib: failed
cannot add library /Applications/Android Emulator.app/Contents/MacOS/emulator/lib64/vulkan/libvulkan.dylib: failed
cannot add library /Applications/Android Emulator.app/Contents/MacOS/emulator/qemu/darwin-aarch64/lib64/vulkan/libMoltenVK.dylib: failed
added library /Applications/Android Emulator.app/Contents/MacOS/emulator/lib64/vulkan/libMoltenVK.dylib
[mvk-info] MoltenVK version 1.1.1. Vulkan version 1.1.154.
	The following 70 Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_create_renderpass2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_depth_stencil_resolve v1
		VK_KHR_descriptor_update_template v1
		VK_KHR_device_group v4
		VK_KHR_device_group_creation v1
		VK_KHR_driver_properties v1
		VK_KHR_external_fence v1
		VK_KHR_external_fence_capabilities v1
		VK_KHR_external_memory v1
		VK_KHR_external_memory_capabilities v1
		VK_KHR_external_semaphore v1
		VK_KHR_external_semaphore_capabilities v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
		VK_KHR_multiview v1
		VK_KHR_portability_subset v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v3
		VK_KHR_sampler_ycbcr_conversion v14
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float16_int8 v1
		VK_KHR_shader_subgroup_extended_types v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_timeline_semaphore v2
		VK_KHR_uniform_buffer_standard_layout v1
		VK_KHR_variable_pointers v1
		VK_EXT_debug_marker v4
		VK_EXT_debug_report v9
		VK_EXT_debug_utils v2
		VK_EXT_descriptor_indexing v2
		VK_EXT_fragment_shader_interlock v1
		VK_EXT_hdr_metadata v2
		VK_EXT_host_query_reset v1
		VK_EXT_image_robustness v1
		VK_EXT_inline_uniform_block v1
		VK_EXT_memory_budget v1
		VK_EXT_metal_surface v1
		VK_EXT_post_depth_coverage v1
		VK_EXT_private_data v1
		VK_EXT_robustness2 v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_swapchain_colorspace v4
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_texture_compression_astc_hdr v1
		VK_EXT_vertex_attribute_divisor v3
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_image_load_store_lod v1
		VK_AMD_shader_trinary_minmax v1
		VK_IMG_format_pvrtc v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v29
		VK_NV_glsl_shader v1
[mvk-info] GPU device:
		model: Apple A12Z
		type: Discrete
		vendorID: 0x106b
		deviceID: 0xa120
		pipelineCacheUUID: 00002775-0400-03ED-9EC6-7EDC4219F216
	supports the following Metal Versions, GPU's and Feature Sets:
		Metal Shading Language 2.3
		GPU Family Apple 5
		GPU Family Apple 4
		GPU Family Apple 3
		GPU Family Apple 2
		GPU Family Apple 1
		GPU Family Mac 2
		GPU Family Mac 1
		GPU Family Common 3
		GPU Family Common 2
		GPU Family Common 1
		macOS GPU Family 2 v1
		macOS GPU Family 1 v4
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
[mvk-info] Created VkInstance with the following 0 Vulkan extensions enabled:
[mvk-info] Using MTLFence for Vulkan semaphores.
[mvk-info] Created VkDevice to run on GPU Apple A12Z with the following 0 Vulkan extensions enabled:
emulator: INFO: ignore sdcard for arm at api level >= 30
HVF error: HV_UNSUPPORTED
qemu-system-aarch64: failed to initialize HVF: Invalid argument

**Comment by 741g** [comment]
@SlonGL This is a known issue; M1 SoC is a requirement. The DTK's do not support hardware ARM64 virtualization.

**Comment by Elijen** [comment]
I'll close the issue since the original problem was resolved, thanks again @741g

**Comment by SlonGL** [comment]
> @SlonGL This is a known issue; M1 SoC is a requirement. The DTK's do not support hardware ARM64 virtualization.

Thanks a lot for the quick reply. It's bad news for me. :(
