### ISSUE TITLE
Audio

### ISSUE THREAD

**Issue by hannesa2** [741g/android-emulator-m1-preview#10]
@741g 
Related to [this change](https://github.com/741g/android-emulator-m1-preview/commit/200d668602858d01f5c310d17a9052fdff7f777c#diff-752180eb8dc62c50aabe89619582363f65cb62ee49284c846d82ed7fe156cd1bL10), does the audio should works now ?
I observed neither audio-out, nor audio-in works. But I only tested with first version

**Comment by 741g** [comment]
Yes, you'll need the latest preview.

**Comment by hannesa2** [comment]
Hmm, I use your Emulater v2 and audio recorder https://github.com/hannesa2/AudioRecorder.git 

When I start record (after apply all permissions manually) 

![image](https://user-images.githubusercontent.com/3314607/102501087-51a83580-407d-11eb-9850-fb15684772f6.png)

I run into 
![image](https://user-images.githubusercontent.com/3314607/102501272-89af7880-407d-11eb-8639-aabf9cf00165.png)

and I see a lot of 

![image](https://user-images.githubusercontent.com/3314607/102501423-b6fc2680-407d-11eb-9c5e-6d0744deb529.png)

How do you make it work, or how should I test it ? 
Do you have any advice ?

**Comment by 741g** [comment]
Does audio output work? This looks like an audio codec issue. You may want to try the Google APIs image: https://github.com/google/android-emulator-m1-preview/releases/tag/0.3

**Comment by hannesa2** [comment]
I can confirm audio out on V3 works. I tested simply with youtube.

Unfortunately record (audio-in) was not successful. Even with lowest quality 
![image](https://user-images.githubusercontent.com/3314607/102509972-71dcf200-4087-11eb-9422-1e34a10de787.png)

**Comment by 741g** [comment]
Thanks for trying it out! We're aware of the audio-in issues and have been investigating fixes.

**Comment by 741g** [comment]
We've just landed some fixes for audio; record should work now (provided you still go to the .. menu and go to Microphone > Virtual headset uses host audio and toggle it on each startup (This is for privacy reasons)) Can you try using the emulator from https://ci.android.com/builds/submitted/7123544/aarch64_sdk_tools_mac/latest/sdk-repo-darwin_aarch64-emulator-7123544.zip and creating an Android R arm64v8a AVD from Android Studio?

**Comment by hannesa2** [comment]
@741g 
I need your help.
I downloaded the [zip](https://ci.android.com/builds/submitted/7123544/aarch64_sdk_tools_mac/latest/sdk-repo-darwin_aarch64-emulator-7123544.zip) and started extracted

`./emulator`

But I run into this 
<img width="258" alt="image" src="https://user-images.githubusercontent.com/3314607/106934530-8306be80-671a-11eb-86fa-050f47f0de36.png">

How to start it ?

**Comment by 741g** [comment]
This could be due to Gatekeeper. You might want to curl or wget that url in the terminal.

**Comment by 741g** [comment]
Hmm, those downloads require a cookie. Hold on

**Comment by 741g** [comment]
Try `wget https://github.com/741g/android-emulator-m1-preview/releases/download/7123544/sdk-repo-darwin_aarch64-emulator-7123544.zip`

**Comment by hannesa2** [comment]
Ok, it looks now better

<img width="703" alt="image" src="https://user-images.githubusercontent.com/3314607/106939145-26a69d80-6720-11eb-9c3f-9dc851294532.png">

<img width="502" alt="image" src="https://user-images.githubusercontent.com/3314607/106939171-30c89c00-6720-11eb-95c8-096c7a33b88d.png">

Is there a way to integrate it seamless ?

I guess this is the right one
![image](https://user-images.githubusercontent.com/3314607/106939856-1cd16a00-6721-11eb-97fa-ed0e079612bd.png)

**Comment by hannesa2** [comment]
I hope this is the right version 

![image](https://user-images.githubusercontent.com/3314607/106941312-f4e30600-6722-11eb-8323-fac135356a94.png)

Anyway, now I can record and play the audio again with Emulator.
This is a huge step forward, now even https://issuetracker.google.com/issues/157223337 is more or less obsolete 🍾 🌈

**Comment by 741g** [comment]
Yes, that should be it! We're also working on better integration w/ Studio so you won't have to manually wget or export ANDROID_SDK_ROOT for the M1 version.

**Comment by hannesa2** [comment]
I did 
```
wget https://github.com/741g/android-emulator-m1-preview/releases/download/7123544/sdk-repo-darwin_aarch64-emulator-7123544.zip -P ~/Downloads
unzip ~/Downloads/sdk-repo-darwin_aarch64-emulator-7123544.zip -d ~/Downloads
mv ~/Library/Android/sdk/emulator ~/Library/Android/sdk/emulator.save
mv ~/Downloads/emulator ~/Library/Android/sdk
```
With it, it works in Android studio seamless

**Comment by trickeyd** [comment]
I've downloaded and moved to the location as described, but I get this whenever I try to use the executable. 
![Screenshot 2021-02-18 at 23 15 38](https://user-images.githubusercontent.com/1107295/108434234-386b6300-723f-11eb-97e5-4d6c694df10e.png)
That was from `./emulator -avd [name]`
-list-avds works fine actually

Any thought? Thanks

**Comment by hannesa2** [comment]
@trickeyd 
I updated my 4 lines script.
My installation was broken during IDE update and I run my script again and it's still working seamless in Android Studio.
Even audio in/out works with my [script](https://github.com/741g/android-emulator-m1-preview/issues/10#issuecomment-773545412)

**Comment by hannesa2** [comment]
> Yes, that should be it! We're also working on better integration w/ Studio so you won't have to manually wget or export ANDROID_SDK_ROOT for the M1 version.

@741g
Let me know, when here is an update. So I can test it for you

**Comment by hannesa2** [comment]
My last working Emulator version was `30.7.4`, some of new was working too but I don't know exactly.
Currently I've blocking microphone issues with `30.8.4`, that's why **I want to downgrade my Emulator.**

I already asked for `30.7.4` download link https://issuetracker.google.com/issues/157223337 but without response.

*  Is there a way to browse Google maven repo
* does someone knows the 30.7.4 download link ?

**Comment by hannesa2** [comment]
It works super nice with `30.9.4`

**Comment by Splint3r7** [comment]
> Try `wget https://github.com/741g/android-emulator-m1-preview/releases/download/7123544/sdk-repo-darwin_aarch64-emulator-7123544.zip`

Thanks this worked. I was getting the same error "emulator" is damaged. 

🚀 🚀 🚀
