### ISSUE TITLE
Attempting to change ADB path causes spinning wheel of death

### ISSUE THREAD

**Issue by PlanetWilson** [741g/android-emulator-m1-preview#11]
I hadn't downloaded ADB so it didn't detect a location, once I had downloaded I couldn't then manually select a location as it pinwheels and I have to kill the app. It isn't possible to simply type into the path box either.

M1 MacBook Air, 16GB / 512GB, macOS 11.1

**Comment by 741g** [comment]
Hi, this is only an issue in the first preview. Can you try again with the latest preview?

**Comment by chixxi** [comment]
Works for me in v2 and v3.

**Comment by PlanetWilson** [comment]
Yes I confirmed that in the main Google repo which I think is the preferred one now.
