### ISSUE TITLE
“Android Emulator” cannot be opened because the developer cannot be verified. 

### ISSUE THREAD

**Issue by abbas-25** [741g/android-emulator-m1-preview#17]
I am not able to launch the latest release as I can't bypass the developer verification ON THE LATEST RELEASE. I was able to bypass and launch it on the most initial release of emulator though.

Any ideas? Is this a problem on my end?

**Comment by 741g** [comment]
Can you try going to Preferences > Security & Privacy and see if the emulator shows up there? Alternatively, you can try curl-ing the Github release url directly, which will bypass quarantine as you haven't downloaded through a browser.

**Comment by samuelalake** [comment]
> Can you try going to Preferences > Security & Privacy and see if the emulator shows up there? Alternatively, you can try curl-ing the Github release url directly, which will bypass quarantine as you haven't downloaded through a browser.

please what is the command for curl-ling the release from the terminal?

**Comment by abbas-25** [comment]
> Can you try going to Preferences > Security & Privacy and see if the emulator shows up there? Alternatively, you can try curl-ing the Github release url directly, which will bypass quarantine as you haven't downloaded it through a browser.

I couldn't find it in preferences. Tried curling, but couldn't download the file. Maybe I am using the wrong URL, can you please share the release URL?
Thanks!

**Comment by Vishram1123** [comment]
Right click and then click open, or go to Show Package Contents/Contents/MacOS/runemu to start the emulator.

**Comment by abbas-25** [comment]
> Right click and then click open, or go to Show Package Contents/Contents/MacOS/runemu to start the emulator.

Right click and open works! I'm pretty new to MacOS. Thanks!
