### ISSUE TITLE
Can't edit emulator's density 

### ISSUE THREAD

**Issue by NevoSaporta** [741g/android-emulator-m1-preview#18]
I'm trying to create an emulator with a different density , but whenever i assign a new value for `hw.lcd.density` which isn't 420 (the default value) the emulator won't open

**Comment by hannesa2** [comment]
This works for me

`hw.lcd.density=120`

I use an own Emulator for this setting

**Comment by NevoSaporta** [comment]
I duplicated the emulator , and i changed the values of `hw.lcd.height and hw.lcd.width` and it worked , but when i changed the value of `hw.lcd.density` (in this case to 405 ) the emulator stopped working

**Comment by hannesa2** [comment]
As far as I remember, when you start on command line, it tells you about all possible values. 405 is not a valid one.

I hope this helps

**Comment by NevoSaporta** [comment]
I started it from the command line , i saw only the lists of the supported `Vulkan extensions ` and the `GPU's and Feature Sets`

**Comment by hannesa2** [comment]
When I set a wrong value 
```
hw.lcd.density=121
hw.lcd.height=720
hw.lcd.width=1920
```
in `config.ini`
and start with CLI `./MacOS/runemu `
I see all possible values

```
mvk-info] Created VkInstance with the following 0 Vulkan extensions enabled:
[mvk-info] Using MTLFence for Vulkan semaphores.
[mvk-info] Created VkDevice to run on GPU Apple M1 with the following 0 Vulkan extensions enabled:
emulator: INFO: ignore sdcard for arm at api level >= 30
qemu: Bad LCD density: 121. Available densities are: 120, 140, 160, 180, 213, 240, 280, 320, 360, 400, 420, 440, 480, 560, 640.
```

Using one of them works for me

**Comment by NevoSaporta** [comment]
Found it , thanks!
