### ISSUE TITLE
Is writable-system supported?

### ISSUE THREAD

**Issue by Androz2091** [741g/android-emulator-m1-preview#19]
Hello, is the `writable-system` option supported? If so, how can I pass it to the emulator? I can't see it in the config.ini file.
And thank you for your work! 😄

**Comment by 741g** [comment]
Hi, sorry for the delay---it's not well supported. You have to use an Android aosp-master platform build targeting sdk_phone64_$ARCH-userdebug (M1: ARCH=arm64) and build it with BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 2 . `-writable-system` is to be passed on the command line. `runemu` in the `/Applications/Android Emulator.app` will show the current command line flags.

**Comment by Androz2091** [comment]
Okay, I think it will be easier to use another computer for the moment :joy:
Thank you anyway 👍
