### ISSUE TITLE
Screenshot resulting in blank PNG

### ISSUE THREAD

**Issue by chixxi** [741g/android-emulator-m1-preview#6]
Whenever I try to make a screenshot the result is an "empty" or "white" PNG File. This is independant from the choosen resolution, density or open app.

Example:
![Screenshot_1607602370](https://user-images.githubusercontent.com/1770007/101771021-99f9ad80-3ae9-11eb-9bbc-b0f49f184b2a.png)

**Comment by 741g** [comment]
Thanks for bringing this up, fix inc in https://android-review.googlesource.com/c/platform/external/qemu/+/1524438

**Comment by 741g** [comment]
This should be available in the latest rev of the v2 preview.

**Comment by chixxi** [comment]
Works for me in v3. Thanks for the quick fix!
