### ISSUE TITLE
Settings App crashes when changing system navigation

### ISSUE THREAD

**Issue by chixxi** [741g/android-emulator-m1-preview#7]
When going to the Settings->Accesibility->System-Navigation and clicking on it with the idea to disable the 3-button-navigation the settings app crashes.

**Comment by 741g** [comment]
Thanks for raising this; we have an internal build of a system image where this isn't an issue. Fix is planned to come out in a future release.

**Comment by chixxi** [comment]
Works in v3. Thanks!
