### ISSUE TITLE
When is there an M1 version of Android Studio

### ISSUE THREAD

**Issue by lewzao** [741g/android-emulator-m1-preview#9]
When is there an M1 version of Android Studio

**Comment by shatyuka** [comment]
Currently in development I think. However IntelliJ IDEA just released a preview version, so Android Studio maybe not very far.

**Comment by shaunsingh** [comment]
Intellij idea released a stable apple silicon version with version 20.3.1, and for android development obviously its missing quite a few features, but it runs much much smoother than android studio

Hopefully the apple silicon version of android studio isn't far away

**Comment by DanMossa** [comment]
@shaunsingh Is there a sort of github issue I could follow?

**Comment by lewb1** [comment]
https://androidstudio.googleblog.com/2021/04/android-studio-arctic-fox-canary-15.html
